# These are supported funding model platforms
github: [soybenja]
patreon: ['https://patreon.com/']
open_collective: # Replace with a single Open Collective username
ko_fi: ['https://ko-fi.com/']
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['https://dashboard.infinitywa.xyz', 'https://www.cafirexos.com/', 'https://boxmineworld.com/', 'https://dash.vortexuscloud.com/login']
